// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _04_Delete_Wall_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04_Delete_Wall_class));
        
        string IMigrationMetadata.Id
        {
            get { return "201612072216048_0.4_Delete_Wall_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
