// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02_Fix_groups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_Fix_groups));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071922196_0.2_Fix_groups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
