// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06_None_Generated_UserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06_None_Generated_UserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201612090819490_0.6_None_Generated_UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
