// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01_Add_a_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_Add_a_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071849292_0.1_Add_a_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
