// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _08_Add_FromUser_Field_To_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08_Add_FromUser_Field_To_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "201701081702438_0.8_Add_FromUser_Field_To_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
