// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _013_Add_AvgWallsPostReaction_field_to_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_013_Add_AvgWallsPostReaction_field_to_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111140592_0.13_Add_AvgWallsPostReaction_field_to_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
