// <auto-generated />
namespace VkDatabaseDll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _010_Autogenerated_Id_Fields_for_Post_and_Photos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_010_Autogenerated_Id_Fields_for_Post_and_Photos));
        
        string IMigrationMetadata.Id
        {
            get { return "201701110916007_0.10_Autogenerated_Id_Fields_for_Post_and_Photos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
