namespace VkDatabaseDll.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _010_Autogenerated_Id_Fields_for_Post_and_Photos : DbMigration
    {
        public override void Up()
        {
            //DropForeignKey("dbo.Posts", "FromUser_VkId", "dbo.Users");
            //DropForeignKey("dbo.Posts", "Owner_VkId", "dbo.Users");
            DropForeignKey("dbo.PostAttachments", "Post_Id", "dbo.Posts");
            DropForeignKey("dbo.PostAttachments", "Photo_Id", "dbo.Photos");
            //DropIndex("dbo.Posts", new[] { "FromUser_VkId" });
            //DropIndex("dbo.Posts", new[] { "Owner_VkId" });
            DropPrimaryKey("dbo.Posts");
            DropPrimaryKey("dbo.Photos");
            AlterColumn("dbo.Posts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Photos", "Id", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.Posts", "Id");
            AddPrimaryKey("dbo.Photos", "Id");
            AddForeignKey("dbo.PostAttachments", "Post_Id", "dbo.Posts", "Id");
            AddForeignKey("dbo.PostAttachments", "Photo_Id", "dbo.Photos", "Id");
            //DropColumn("dbo.Posts", "FromUser_VkId");
            //DropColumn("dbo.Posts", "Owner_VkId");
        }
        
        public override void Down()
        {
            //AddColumn("dbo.Posts", "Owner_VkId", c => c.Int());
            //AddColumn("dbo.Posts", "FromUser_VkId", c => c.Int());
            DropForeignKey("dbo.PostAttachments", "Photo_Id", "dbo.Photos");
            DropForeignKey("dbo.PostAttachments", "Post_Id", "dbo.Posts");
            DropPrimaryKey("dbo.Photos");
            DropPrimaryKey("dbo.Posts");
            AlterColumn("dbo.Photos", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Posts", "Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Photos", "Id");
            AddPrimaryKey("dbo.Posts", "Id");
            //CreateIndex("dbo.Posts", "Owner_VkId");
            //CreateIndex("dbo.Posts", "FromUser_VkId");
            AddForeignKey("dbo.PostAttachments", "Photo_Id", "dbo.Photos", "Id");
            AddForeignKey("dbo.PostAttachments", "Post_Id", "dbo.Posts", "Id");
            //AddForeignKey("dbo.Posts", "Owner_VkId", "dbo.Users", "VkId");
            //AddForeignKey("dbo.Posts", "FromUser_VkId", "dbo.Users", "VkId");
        }
    }
}
